$(document).ready(function(){
    $(".nav__btn").click(function(){
        $(".nav__list").toggle();
        $(".nav__btn__icon").toggleClass("active");
    });
    $(".nav__btn").on("tap",
        function(){
            $(".nav__list").toggle();
            $(".nav__btn__icon").toggleClass("active");
    });
    $(".nav__link").click(function(){
        $(".nav__link").removeClass("nav__link--active");
        $(this).addClass("nav__link--active");
    });
    $(".section__post__btn").on("tap",
        function(){
            $(this).addClass("btn--touched");
    });
    $(".section__post__btn").on("click",
        function(){
            $(this).addClass("btn--touched");
    });
    $(".social__item").on("tap",
        function(){
            $(".social__item").removeClass("btn--touched");
            $(this).addClass("btn--touched");
    });
    $(".social__item").on("click",
        function(){
            $(".social__item").removeClass("btn--touched");
            $(this).addClass("btn--touched");
    });
});